on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 20.9.0
          - 20.8.1
          - 20.8.0
          - 20.7.0
          - 20.6.1
          - 20.6.0
          - 20.5.1
          - 20.5.0
          - 20.4.0
          - 20.3.1
          - 20.3.0
          - 20.2.0
          - 20.1.0
          - 20.0.0
          - 18.19.1
          - 18.19.0
          - 18.18.2
          - 18.18.1
          - 18.18.0
          - 18.17.1
          - 18.17.0
          - 18.16.1
          - 18.16.0
          - 18.15.0
          - 18.14.2
          - 18.14.1
          - 18.14.0
          - 18.13.0
          - 18.12.1
          - 18.12.0
          - 18.11.0
          - 18.10.0
          - 18.9.1
          - 18.9.0
          - 18.8.0
          - 18.7.0
          - 18.6.0
          - 18.5.0
          - 18.4.0
          - 18.3.0
          - 18.2.0
          - 18.1.0
          - 18.0.0
          - 16.20.2
          - 14.21.3
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Cachix
        uses: cachix/cachix-action@v14
        with:
          name: fontis
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build ${{ matrix.version }}
        run: nix build .#${{ matrix.version }}
      - name: Publish ${{ matrix.version }}
        run: cachix push fontis `cd -P result && pwd`
