on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 20.9.0
          - 20.8.1
          - 20.8.0
          - 20.7.0
          - 20.6.1
          - 20.6.0
          - 20.5.1
          - 20.5.0
          - 20.4.0
          - 20.3.1
          - 20.3.0
          - 20.2.0
          - 20.1.0
          - 20.0.0
          - 18.18.2
          - 18.18.1
          - 18.18.0
          - 18.17.1
          - 18.17.0
          - 18.16.1
          - 18.16.0
          - 18.15.0
          - 18.14.2
          - 18.14.1
          - 18.14.0
          - 18.13.0
          - 18.12.1
          - 18.12.0
          - 18.11.0
          - 18.10.0
          - 18.9.1
          - 18.9.0
          - 18.8.0
          - 18.7.0
          - 18.6.0
          - 18.5.0
          - 18.4.0
          - 18.3.0
          - 18.2.0
          - 18.1.0
          - 18.0.0
          - 16.20.2
          - 16.20.1
          - 16.20.0
          - 16.19.1
          - 16.19.0
          - 16.18.1
          - 16.18.0
          - 16.17.1
          - 16.17.0
          - 16.16.0
          - 16.15.1
          - 16.15.0
          - 16.14.2
          - 16.14.1
          - 16.14.0
          - 16.13.2
          - 16.13.1
          - 16.13.0
          - 16.12.0
          - 16.11.1
          - 16.11.0
          - 16.10.0
          - 16.9.1
          - 16.9.0
          - 16.8.0
          - 16.7.0
          - 16.6.2
          - 16.6.1
          - 16.6.0
          - 16.5.0
          - 16.4.2
          - 16.4.1
          - 16.4.0
          - 16.3.0
          - 16.2.0
          - 16.1.0
          - 16.0.0
          - 14.21.3
          - 14.21.2
          - 14.21.1
          - 14.21.0
          - 14.20.1
          - 14.20.0
          - 14.19.3
          - 14.19.2
          - 14.19.1
          - 14.19.0
          - 14.18.3
          - 14.18.2
          - 14.18.1
          - 14.18.0
          - 14.17.6
          - 14.17.5
          - 14.17.4
          - 14.17.3
          - 14.17.2
          - 14.17.1
          - 14.17.0
          - 14.16.1
          - 14.16.0
          - 14.15.5
          - 14.15.4
          - 14.15.3
          - 14.15.2
          - 14.15.1
          - 14.15.0
          - 14.14.0
          - 14.13.1
          - 14.13.0
          - 14.12.0
          - 14.11.0
          - 14.10.1
          - 14.10.0
          - 14.9.0
          - 14.8.0
          - 14.7.0
          - 14.6.0
          - 14.5.0
          - 14.4.0
          - 14.3.0
          - 14.2.0
          - 14.1.0
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Cachix
        uses: cachix/cachix-action@v12
        with:
          name: fontis
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build ${{ matrix.version }}
        run: nix build .#${{ matrix.version }}
      - name: Publish ${{ matrix.version }}
        run: cachix push fontis `cd -P result && pwd`
